name: Update Package.swift

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.0.0)"
        required: true
      token:
        description: "GitHub token for authentication"
        required: true
  repository_dispatch:
    types: [update-package]

jobs:
  update-package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ inputs.token }}

      - name: Update Package
        uses: ./.github/actions/update-package
        with:
          version: ${{ github.event.inputs.version || github.event.client_payload.version }}
          github-token: ${{ inputs.token }}
